# Form implementation generated from reading ui file 'reg.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox as mg
from mainwin import Ui_MainWindow
from connector import c,db
from datetime import datetime

userID = None

class Ui_Reg(object):
    def setupUi(self, RegWindow):
        RegWindow.setObjectName("RegWindow")
        RegWindow.resize(447, 321)
        self.centralwidget = QtWidgets.QWidget(parent=RegWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 10, 391, 41))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(140, 10, 131, 20))
        self.label.setStyleSheet("font: 9pt \"W95FA\";")
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(30, 120, 391, 171))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(150, 10, 91, 20))
        self.label_2.setStyleSheet("font: 9pt \"W95FA\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 131, 20))
        self.label_3.setStyleSheet("font: 9pt \"W95FA\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(20, 80, 131, 20))
        self.label_4.setStyleSheet("font: 9pt \"W95FA\";")
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(80, 50, 291, 21))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.lineEdit.setFont(font)
        self.lineEdit.setMaxLength(32767)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 80, 291, 21))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("")
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setMaxLength(32767)
        self.lineEdit_2.setCursorPosition(0)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.checkBox = QtWidgets.QCheckBox(parent=self.frame_2)
        self.checkBox.setGeometry(QtCore.QRect(280, 110, 101, 20))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkBox.toggled.connect(self.hidePassword)
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(10, 120, 171, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(74, 223, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(74, 223, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(74, 223, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(74, 223, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(74, 223, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(74, 223, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(74, 223, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(74, 223, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(74, 223, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        self.pushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(74, 223, 0);\n"
"border-color: rgb(235, 235, 235);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 50, 391, 71))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        RegWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=RegWindow)
        self.statusbar.setObjectName("statusbar")
        RegWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RegWindow)
        QtCore.QMetaObject.connectSlotsByName(RegWindow)

    def retranslateUi(self, RegWindow):
        _translate = QtCore.QCoreApplication.translate
        RegWindow.setWindowTitle(_translate("RegWindow", "RegWindow"))
        self.label.setText(_translate("RegWindow", "WELCOME TO DOTA2"))
        self.label_2.setText(_translate("RegWindow", "JOIN THE BATTLE"))
        self.label_3.setText(_translate("RegWindow", "Nickname:"))
        self.label_4.setText(_translate("RegWindow", "Password:"))
        self.lineEdit.setPlaceholderText(_translate("RegWindow", "Enter your nickname"))
        self.lineEdit_2.setPlaceholderText(_translate("RegWindow", "Enter your account\'s password"))
        self.checkBox.setText(_translate("RegWindow", "Hide password"))
        self.pushButton.setText(_translate("RegWindow", "PLAY FREE NOW"))
        self.pushButton.clicked.connect(self.autorization)
        self.label_5.setText(_translate("RegWindow", "Every day, millions of pIayers worldwide enter the battle as one of over а hundred Dota Heroes in а 5v5 team clash. lt\'s completely tree to play and always be - start defending уоur ancient now."))

    def hidePassword(self,checked):
        if checked:
            self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        else:
            self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
    
    def registration(self,nickname,password):
        global userID
        currentDate = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        c.execute("INSERT INTO player(nickname,level,winValue,looseValue,DateCreate,ratingValue,cristalsValue,avatarPath,statusID,backgroundPath,password) VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)",(nickname,1,0,0,currentDate,0,0,"avatar.jpg",1,None,password,))
        c.execute("LAST_INSERT_ID()")
        userID = c.fetchone()
        self.InitMain()
    
    def autorization(self):
        global userID
        nickname = self.lineEdit.text()
        password = self.lineEdit_2.text()
        if nickname == "":
            mg.warning(None,"Ошибка","Введите логин",mg.StandardButton.Ok)
        else:
            c.execute("SELECT password, ID FROM player WHERE nickname = %s",(nickname,))
            dbPassword = c.fetchone()
            if dbPassword == None:
                if password == "":
                    mg.warning(None,"Ошибка","Введите пароль",mg.StandardButton.Ok)
                else:
                    reply = mg.question(None,"Подтверждение","Вы уверены?",QtWidgets.QMessageBox.StandardButton.Yes | QtWidgets.QMessageBox.StandardButton.No)
                    if reply == mg.StandardButton.Yes:
                        self.registration(nickname,password)
            elif password == dbPassword[0]:
                userID = dbPassword[1]
                self.InitMain()
            else:
                mg.warning(None,"Ошибка","Неверный пароль",mg.StandardButton.Ok)
                
        
    def InitMain(self):
        ui_main.Init(userID)
        RegWindow.hide()
        print(userID)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_Reg()   
    ui_main = Ui_MainWindow()

    MainWindow = QtWidgets.QMainWindow()
    RegWindow = QtWidgets.QMainWindow()
    ui_main.setupUi(MainWindow)
    ui.setupUi(RegWindow)
    MainWindow.show()
    RegWindow.show()
    sys.exit(app.exec())
