# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from connector import c,db
from datetime import datetime
import os
userID = None
authDate = None
currentHeroID = 1
heroImgPath = None

class Ui_MainWindow(object):
    def __init__ (self):
        self.click_count = 0
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(991, 686)
        MainWindow.closeEvent = self.closeEvent
        self.friendProfileID = 0
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.update_timer = QtCore.QTimer()
        self.update_timer.timeout.connect(self.globalUpdate)
        self.update_timer.start(1000) 
        self.click_timer = QtCore.QTimer()
        self.click_timer.setSingleShot(True) 
        self.click_timer.timeout.connect(self.reset_click_count)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(0, 0, 991, 51))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setGeometry(QtCore.QRect(120, 0, 81, 51))
        self.pushButton.setText("")
        self.pushButton.clicked.connect(self.showMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons8-дота-2-48.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(48, 48))
        self.pushButton.setCheckable(False)
        self.pushButton.setDefault(True)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 10, 31, 31))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("w95ico/win95-winxp_icons-master/icons/wxp_246.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 10, 31, 31))
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("w95ico/win95-winxp_icons-master/icons/wxp_255.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("w95ico/win95-winxp_icons-master/icons/w2k_settings.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.HeroesButton = QtWidgets.QPushButton(parent=self.frame)
        self.HeroesButton.setGeometry(QtCore.QRect(204, 0, 81, 51))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.HeroesButton.setFont(font)
        self.HeroesButton.setObjectName("HeroesButton")
        self.HeroesButton.clicked.connect(self.showHero)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(280, 0, 81, 51))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(358, 0, 81, 51))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(437, 0, 81, 51))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_9.setGeometry(QtCore.QRect(516, 0, 81, 51))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(820, 10, 31, 31))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Shards_splash.ico"))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gemsLabel = QtWidgets.QLabel(parent=self.frame)
        self.gemsLabel.setGeometry(QtCore.QRect(850, 10, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gemsLabel.setFont(font)
        self.gemsLabel.setObjectName("gemsLabel")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_10.setGeometry(QtCore.QRect(950, 10, 31, 31))
        self.pushButton_10.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("w95ico/win95-winxp_icons-master/icons/w95_27.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_10.setIcon(icon4)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_11.setGeometry(QtCore.QRect(920, 10, 31, 31))
        self.pushButton_11.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("w95ico/win95-winxp_icons-master/icons/w2k_closed_folder.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_11.setIcon(icon5)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_12.setGeometry(QtCore.QRect(890, 10, 31, 31))
        self.pushButton_12.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("w95ico/win95-winxp_icons-master/icons/w98_envelope_open_sheet.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_12.setIcon(icon6)
        self.pushButton_12.setObjectName("pushButton_12")
        self.profileFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.profileFrame.setGeometry(QtCore.QRect(20, 70, 281, 241))
        self.profileFrame.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.profileFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.profileFrame.setObjectName("profileFrame")
        self.profileFrame.setStyleSheet("background-color: rgb(225, 225, 225);")

        
        self.profileButton = QtWidgets.QPushButton(parent=self.profileFrame)
        self.profileButton.setGeometry(QtCore.QRect(10, 10, 61, 61))
        self.profileButton.setText("")
        
        self.profileButton.setObjectName("profileButton")
        self.profileButton.clicked.connect(self.showProfile)
        self.NicknameLabel = QtWidgets.QLabel(parent=self.profileFrame)
        self.NicknameLabel.setGeometry(QtCore.QRect(80, 10, 101, 16))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.NicknameLabel.setFont(font)
        self.NicknameLabel.setObjectName("NicknameLabel")
        self.StatusLabel = QtWidgets.QLabel(parent=self.profileFrame)
        self.StatusLabel.setGeometry(QtCore.QRect(80, 30, 101, 16))
        self.StatusLabel.setStyleSheet("color: rgb(70, 180, 0);")
        font = QtGui.QFont()
        font.setFamily("W95FA")
        font.setPointSize(8)
        self.StatusLabel.setFont(font)
        self.StatusLabel.setObjectName("StatusLabel")
        self.mmrIcoLabel = QtWidgets.QLabel(parent=self.profileFrame)
        self.mmrIcoLabel.setGeometry(QtCore.QRect(190, -10, 91, 91))
        self.mmrIcoLabel.setText("")
        self.mmrIcoLabel.setPixmap(QtGui.QPixmap("noTitle.png"))
        self.mmrIcoLabel.setScaledContents(True)
        self.mmrIcoLabel.setObjectName("mmrIcoLabel")
        self.favoriteButton3 = QtWidgets.QPushButton(parent=self.profileFrame)
        self.favoriteButton3.setGeometry(QtCore.QRect(190, 80, 81, 61))
        self.favoriteButton3.setText("")
        self.favoriteButton3.setObjectName("favoriteButton3")
        self.favouriteButton2 = QtWidgets.QPushButton(parent=self.profileFrame)
        self.favouriteButton2.setGeometry(QtCore.QRect(100, 80, 81, 61))
        self.favouriteButton2.setText("")
        self.favouriteButton2.setObjectName("favouriteButton2")
        self.favouriteButton1 = QtWidgets.QPushButton(parent=self.profileFrame)
        self.favouriteButton1.setGeometry(QtCore.QRect(10, 80, 81, 61))
        self.favouriteButton1.setText("")
        self.favouriteButton1.setObjectName("favouriteButton1")
        self.frame_3 = QtWidgets.QFrame(parent=self.profileFrame)
        self.frame_3.setGeometry(QtCore.QRect(10, 150, 261, 80))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 111, 20))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(138, 10, 121, 20))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.matchesCountLabel = QtWidgets.QLabel(parent=self.frame_3)
        self.matchesCountLabel.setGeometry(QtCore.QRect(15, 40, 101, 20))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        font.setPointSize(12)
        self.matchesCountLabel.setFont(font)
        self.matchesCountLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.matchesCountLabel.setObjectName("matchesCountLabel")
        self.winsCountLabel = QtWidgets.QLabel(parent=self.frame_3)
        self.winsCountLabel.setGeometry(QtCore.QRect(140, 40, 121, 20))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        font.setPointSize(12)
        self.winsCountLabel.setFont(font)
        self.winsCountLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.winsCountLabel.setObjectName("winsCountLabel")
        self.frame_4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(20, 330, 281, 321))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_4.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.frame_main_layout = QtWidgets.QVBoxLayout(self.frame_4)
        self.frame_main_layout.setContentsMargins(5, 50, 5, 5)  # Отступ сверху для кнопок
        self.frame_main_layout.setSpacing(5)
        self.frame_main_layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        
        
        self.comboBox = QtWidgets.QComboBox(parent=self.frame_4)
        self.comboBox.setGeometry(QtCore.QRect(10, 10, 191, 31))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_addFriend = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushButton_addFriend.setGeometry(QtCore.QRect(210, 10, 31, 31))
        self.pushButton_addFriend.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("w95ico/win95-winxp_icons-master/icons/w98_world_phonereceiver.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_addFriend.setIcon(icon8)
        self.pushButton_addFriend.setObjectName("pushButton_addFriend")
        self.pushButton_addFriend.clicked.connect(self.openAddFriend)
        self.pushButton_22 = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushButton_22.setGeometry(QtCore.QRect(240, 10, 31, 31))
        self.pushButton_22.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("w95ico/win95-winxp_icons-master/icons/w95_18.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_22.setIcon(icon9)
        self.pushButton_22.setObjectName("pushButton_22")
        self.backgroundLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.backgroundLabel.setGeometry(QtCore.QRect(0, 50, 991, 621))
        self.backgroundLabel.setText("")
        self.backgroundLabel.setObjectName("backgroundLabel")
        self.chatWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.chatWidget.setEnabled(True)
        self.chatWidget.setGeometry(QtCore.QRect(310, 460, 481, 191))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.chatWidget.setFont(font)
        self.chatWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.chatWidget.setElideMode(QtCore.Qt.TextElideMode.ElideNone)
        self.chatWidget.setUsesScrollButtons(True)
        self.chatWidget.setDocumentMode(False)
        self.chatWidget.setTabsClosable(False)
        self.chatWidget.setMovable(False)
        self.chatWidget.setTabBarAutoHide(False)
        self.chatWidget.setObjectName("chatWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.chatSendButton = QtWidgets.QPushButton(parent=self.tab)
        self.chatSendButton.setGeometry(QtCore.QRect(400, 140, 75, 24))
        self.chatSendButton.setObjectName("chatSendButton")
        self.chatLineEdit = QtWidgets.QLineEdit(parent=self.tab)
        self.chatLineEdit.setGeometry(QtCore.QRect(10, 142, 381, 20))
        self.chatLineEdit.setObjectName("chatLineEdit")
        self.chatTextEdit = QtWidgets.QTextEdit(parent=self.tab)
        self.chatTextEdit.setGeometry(QtCore.QRect(340, 10, 131, 121))
        self.chatTextEdit.setUndoRedoEnabled(True)
        self.chatTextEdit.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.WidgetWidth)
        self.chatTextEdit.setReadOnly(True)
        self.chatTextEdit.setCursorWidth(0)
        self.chatTextEdit.setObjectName("chatTextEdit")
        self.chatMessages = QtWidgets.QTextEdit(parent=self.tab)
        self.chatMessages.setGeometry(QtCore.QRect(0, 0, 331, 131))
        self.chatMessages.setUndoRedoEnabled(True)
        self.chatMessages.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.WidgetWidth)
        self.chatMessages.setReadOnly(True)
        self.chatMessages.setCursorWidth(0)
        self.chatMessages.setObjectName("chatMessages")
        self.chatWidget.addTab(self.tab, "")
        self.playButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.playButton.setGeometry(QtCore.QRect(800, 610, 171, 41))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.addFriendFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.addFriendFrame.setGeometry(QtCore.QRect(310, 190, 391, 211))
        self.addFriendFrame.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.addFriendFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.addFriendFrame.setObjectName("addFriendFrame")
        self.addFriendFrame.setVisible(False)
        self.addFriendFrame.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.label_friend = QtWidgets.QLabel(parent=self.addFriendFrame)
        self.label_friend.setGeometry(QtCore.QRect(140, 10, 131, 16))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.label_friend.setFont(font)
        self.label_friend.setObjectName("label")
        self.searchFriendLineEdit = QtWidgets.QLineEdit(parent=self.addFriendFrame)
        self.searchFriendLineEdit.setGeometry(QtCore.QRect(10, 40, 371, 22))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.searchFriendLineEdit.setFont(font)
        self.searchFriendLineEdit.setObjectName("searchFriendLineEdit")
        self.searchFriendLineEdit.textChanged.connect(self.searchFriend)
        self.rejectButton = QtWidgets.QPushButton(parent=self.addFriendFrame)
        self.rejectButton.setGeometry(QtCore.QRect(10, 150, 171, 51))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.rejectButton.setFont(font)
        self.rejectButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(207, 0, 0);")
        self.rejectButton.setObjectName("rejectButton")
        self.rejectButton.clicked.connect(self.closeAddFriend)
        self.rejectButton.setEnabled(True)
        
        self.addFriendButton = QtWidgets.QPushButton(parent=self.addFriendFrame)
        self.addFriendButton.setGeometry(QtCore.QRect(210, 150, 171, 51))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.addFriendButton.setFont(font)
        self.addFriendButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(70, 180, 0);")
        self.addFriendButton.setObjectName("addFriendButton")
        self.addFriendButton.clicked.connect(self.addFriend)
        self.addFriendButton.setVisible(False)
        self.searchAvatarlabel = QtWidgets.QLabel(parent=self.addFriendFrame)
        self.searchAvatarlabel.setGeometry(QtCore.QRect(30, 70, 60, 60))
        self.searchAvatarlabel.setText("")
        self.searchAvatarlabel.setPixmap(QtGui.QPixmap("../Desktop/dota/avatar.jpg"))
        self.searchAvatarlabel.setScaledContents(True)
        self.searchAvatarlabel.setObjectName("searchAvatarlabel")
        self.searchAvatarlabel.setVisible(False)
        self.searchNickLabel = QtWidgets.QLabel(parent=self.addFriendFrame)
        self.searchNickLabel.setGeometry(QtCore.QRect(110, 80, 49, 16))
        
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.searchNickLabel.setFont(font)
        self.searchNickLabel.setObjectName("serchNickLabel")
        self.searchNickLabel.setVisible(False)
        self.searchStatusLabel = QtWidgets.QLabel(parent=self.addFriendFrame)
        self.searchStatusLabel.setGeometry(QtCore.QRect(110, 110, 49, 16))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.searchStatusLabel.setFont(font)
        self.searchStatusLabel.setObjectName("searchStatusLabel")
        self.searchStatusLabel.setVisible(False)
        self.playButton.setFont(font)
        self.playButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(70, 211, 0);")
        self.playButton.setObjectName("playButton")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 110, 951, 531))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.profileButtonProfile = QtWidgets.QPushButton(parent=self.tab_2)
        self.profileButtonProfile.setGeometry(QtCore.QRect(10, 10, 130, 130))
        self.profileButtonProfile.setText("")
        self.profileButtonProfile.clicked.connect(self.changeAvatar)
        self.profileButtonProfile.setObjectName("profileButtonProfile")
        self.mmrIcoProfileLabel = QtWidgets.QLabel(parent=self.tab_2)
        self.mmrIcoProfileLabel.setGeometry(QtCore.QRect(0, 110, 91, 91))
        self.mmrIcoProfileLabel.setText("")
        self.mmrIcoProfileLabel.setPixmap(QtGui.QPixmap("noTitle.png"))
        self.mmrIcoProfileLabel.setScaledContents(True)
        self.mmrIcoProfileLabel.setObjectName("mmrIcoProfileLabel")
        self.StatusLabelProfile = QtWidgets.QLabel(parent=self.tab_2)
        self.StatusLabelProfile.setGeometry(QtCore.QRect(150, 30, 141, 16))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        font.setPointSize(10)
        self.StatusLabelProfile.setFont(font)
        self.StatusLabelProfile.setObjectName("StatusLabelProfile")
        self.NicknameLabelProfile = QtWidgets.QLabel(parent=self.tab_2)
        self.NicknameLabelProfile.setGeometry(QtCore.QRect(150, 10, 151, 16))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        font.setPointSize(11)
        self.NicknameLabelProfile.setFont(font)
        self.NicknameLabelProfile.setObjectName("NicknameLabelProfile")
        self.favouriteButton1Profile = QtWidgets.QPushButton(parent=self.tab_2)
        self.favouriteButton1Profile.setGeometry(QtCore.QRect(150, 90, 71, 51))
        self.favouriteButton1Profile.setText("")
        self.favouriteButton1Profile.setObjectName("favouriteButton1Profile")
        self.favouriteButton1Profile.clicked.connect(lambda: self.setFavourite(1))
        self.favouriteButton2Profile = QtWidgets.QPushButton(parent=self.tab_2)
        self.favouriteButton2Profile.setGeometry(QtCore.QRect(230, 90, 71, 51))
        self.favouriteButton2Profile.setText("")
        self.favouriteButton2Profile.setObjectName("favouriteButton2Profile")
        self.favouriteButton2Profile.clicked.connect(lambda: self.setFavourite(2))
        self.favouriteButton3Profile = QtWidgets.QPushButton(parent=self.tab_2)
        self.favouriteButton3Profile.setGeometry(QtCore.QRect(310, 90, 71, 51))
        self.favouriteButton3Profile.setText("")
        self.favouriteButton3Profile.setObjectName("favoriteButton3Profile")
        self.favouriteButton3Profile.clicked.connect(lambda: self.setFavourite(3))
        self.frame_6 = QtWidgets.QFrame(parent=self.tab_2)
        self.frame_6.setGeometry(QtCore.QRect(130, 150, 261, 81))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 111, 20))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_9.setGeometry(QtCore.QRect(138, 10, 121, 20))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.machesCountProfileLabel = QtWidgets.QLabel(parent=self.frame_6)
        self.machesCountProfileLabel.setGeometry(QtCore.QRect(15, 40, 101, 20))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        font.setPointSize(12)
        self.machesCountProfileLabel.setFont(font)
        self.machesCountProfileLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.machesCountProfileLabel.setObjectName("machesCountProfileLabel")
        self.winsCountProfileLabel = QtWidgets.QLabel(parent=self.frame_6)
        self.winsCountProfileLabel.setGeometry(QtCore.QRect(140, 40, 121, 20))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        font.setPointSize(12)
        self.winsCountProfileLabel.setFont(font)
        self.winsCountProfileLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.winsCountProfileLabel.setObjectName("winsCountProfileLabel")
        self.frame_7 = QtWidgets.QFrame(parent=self.tab_2)
        self.frame_7.setGeometry(QtCore.QRect(130, 240, 261, 81))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_17 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_17.setGeometry(QtCore.QRect(10, 10, 111, 20))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_18.setGeometry(QtCore.QRect(138, 10, 121, 20))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.dateInGameLabel = QtWidgets.QLabel(parent=self.frame_7)
        self.dateInGameLabel.setGeometry(QtCore.QRect(15, 40, 101, 20))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        font.setPointSize(12)
        self.dateInGameLabel.setFont(font)
        self.dateInGameLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dateInGameLabel.setObjectName("dateInGameLabel")
        self.levelLabel = QtWidgets.QLabel(parent=self.frame_7)
        self.levelLabel.setGeometry(QtCore.QRect(140, 40, 121, 20))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        font.setPointSize(12)
        self.levelLabel.setFont(font)
        self.levelLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.levelLabel.setObjectName("levelLabel")
        self.friendIDLabel = QtWidgets.QLabel(parent=self.tab_2)
        self.friendIDLabel.setGeometry(QtCore.QRect(370, 60, 71, 16))
        self.friendIDLabel.setObjectName("friendIDLabel")
        self.addedFriendLabel = QtWidgets.QLabel(parent = self.tab_2)
        self.addedFriendLabel.setGeometry(QtCore.QRect(440, 80, 71, 16))
        self.addedFriendLabel.setObjectName("addedFriendLabel")
        self.addedFriendLabel.setText("")
        self.deleteFriendButton = QtWidgets.QPushButton(parent=self.tab_2)
        self.deleteFriendButton.setGeometry(QtCore.QRect(440, 40, 25, 25))
        self.deleteFriendButton.setObjectName("deleteFriendButton")
        self.deleteFriendButton.setText("X")
        self.deleteFriendButton.clicked.connect(self.deleteFriend)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.strangeLeftFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.strangeLeftFrame.setGeometry(QtCore.QRect(20, 90, 291, 171))
        self.strangeLeftFrame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.strangeLeftFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.strangeLeftFrame.setObjectName("strangeLeftFrame")
        self.strangeRightFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.strangeRightFrame.setGeometry(QtCore.QRect(330, 90, 291, 171))
        self.strangeRightFrame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.strangeRightFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.strangeRightFrame.setObjectName("strangeRightFrame")
        self.agilityLeftFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.agilityLeftFrame.setGeometry(QtCore.QRect(20, 280, 291, 171))
        self.agilityLeftFrame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.agilityLeftFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.agilityLeftFrame.setObjectName("agilityLeftFrame")
        self.agilityRightFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.agilityRightFrame.setGeometry(QtCore.QRect(330, 280, 291, 171))
        self.agilityRightFrame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.agilityRightFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.agilityRightFrame.setObjectName("agilityRightFrame")
        self.intLeftFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.intLeftFrame.setGeometry(QtCore.QRect(20, 470, 291, 171))
        self.intLeftFrame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.intLeftFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.intLeftFrame.setObjectName("intLeftFrame")
        self.intRightFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.intRightFrame.setGeometry(QtCore.QRect(330, 470, 291, 171))
        self.intRightFrame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.intRightFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.intRightFrame.setObjectName("intRightFrame")
        self.strl = QtWidgets.QLabel(parent=self.centralwidget)
        self.strl.setGeometry(QtCore.QRect(20, 70, 71, 16))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.strl.setFont(font)
        self.strl.setStyleSheet("color: rgb(170, 0, 0);")
        self.strl.setObjectName("strl")
        self.strr = QtWidgets.QLabel(parent=self.centralwidget)
        self.strr.setGeometry(QtCore.QRect(330, 70, 71, 16))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.strr.setFont(font)
        self.strr.setStyleSheet("color: rgb(170, 0, 0);")
        self.strr.setObjectName("strr")
        self.agl = QtWidgets.QLabel(parent=self.centralwidget)
        self.agl.setGeometry(QtCore.QRect(20, 260, 71, 16))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.agl.setFont(font)
        self.agl.setStyleSheet("color: rgb(170, 0, 0);")
        self.agl.setObjectName("agl")
        self.agr = QtWidgets.QLabel(parent=self.centralwidget)
        self.agr.setGeometry(QtCore.QRect(330, 260, 71, 16))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.agr.setFont(font)
        self.agr.setStyleSheet("color: rgb(170, 0, 0);")
        self.agr.setObjectName("agr")
        self.intr = QtWidgets.QLabel(parent=self.centralwidget)
        self.intr.setGeometry(QtCore.QRect(330, 450, 81, 16))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.intr.setFont(font)
        self.intr.setStyleSheet("color: rgb(170, 0, 0);")
        self.intr.setObjectName("intr")
        self.intl = QtWidgets.QLabel(parent=self.centralwidget)
        self.intl.setGeometry(QtCore.QRect(20, 450, 81, 16))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.intl.setFont(font)
        self.intl.setStyleSheet("color: rgb(170, 0, 0);")
        self.intl.setObjectName("intl")
        self.HeroTabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.HeroTabWidget.setGeometry(QtCore.QRect(630, 70, 351, 571))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.HeroTabWidget.setFont(font)
        self.HeroTabWidget.setObjectName("HeroTabWidget")
        self.SUMMARY = QtWidgets.QWidget()
        self.SUMMARY.setObjectName("SUMMARY")
        self.heroIcoLabel = QtWidgets.QLabel(parent=self.SUMMARY)
        self.heroIcoLabel.setGeometry(QtCore.QRect(10, 10, 91, 51))
        self.heroIcoLabel.setText("")
        self.heroIcoLabel.setObjectName("heroIcoLabel")
        self.heroNameLabel = QtWidgets.QLabel(parent=self.SUMMARY)
        self.heroNameLabel.setGeometry(QtCore.QRect(120, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        font.setPointSize(11)
        self.heroNameLabel.setFont(font)
        self.heroNameLabel.setObjectName("heroNameLabel")
        self.sideLabel = QtWidgets.QLabel(parent=self.SUMMARY)
        self.sideLabel.setGeometry(QtCore.QRect(10, 90, 49, 16))
        self.sideLabel.setObjectName("sideLabel")
        self.strIco = QtWidgets.QLabel(parent=self.SUMMARY)
        self.strIco.setGeometry(QtCore.QRect(10, 120, 61, 31))
        self.strIco.setText("")
        self.strIco.setPixmap(QtGui.QPixmap("Strength_attribute_symbol.png"))
        self.strIco.setObjectName("strIco")
        self.aglIco = QtWidgets.QLabel(parent=self.SUMMARY)
        self.aglIco.setGeometry(QtCore.QRect(10, 160, 61, 31))
        self.aglIco.setText("")
        self.aglIco.setPixmap(QtGui.QPixmap("Agility_attribute_symbol.png"))
        self.aglIco.setScaledContents(False)
        self.aglIco.setObjectName("aglIco")
        self.intIco = QtWidgets.QLabel(parent=self.SUMMARY)
        self.intIco.setGeometry(QtCore.QRect(10, 200, 61, 31))
        self.intIco.setText("")
        self.intIco.setPixmap(QtGui.QPixmap("Intelligence_attribute_symbol.png"))
        self.intIco.setObjectName("intIco")
        self.strValueLabel = QtWidgets.QLabel(parent=self.SUMMARY)
        self.strValueLabel.setGeometry(QtCore.QRect(80, 120, 61, 31))
        self.strValueLabel.setObjectName("strValueLabel")
        self.aglValueLabel = QtWidgets.QLabel(parent=self.SUMMARY)
        self.aglValueLabel.setGeometry(QtCore.QRect(80, 160, 61, 31))
        self.aglValueLabel.setObjectName("aglValueLabel")
        self.intValueLabel = QtWidgets.QLabel(parent=self.SUMMARY)
        self.intValueLabel.setGeometry(QtCore.QRect(80, 200, 61, 31))
        self.intValueLabel.setObjectName("intValueLabel")
        self.label_role = QtWidgets.QLabel(parent=self.SUMMARY)
        self.label_role.setGeometry(QtCore.QRect(10, 240, 49, 16))
        self.label_role.setObjectName("label_role")
        self.roleValueLabel = QtWidgets.QLabel(parent=self.SUMMARY)
        self.roleValueLabel.setGeometry(QtCore.QRect(10, 270, 49, 16))
        self.roleValueLabel.setObjectName("roleValueLabel")
        self.label_role_2 = QtWidgets.QLabel(parent=self.SUMMARY)
        self.label_role_2.setGeometry(QtCore.QRect(10, 300, 49, 16))
        self.label_role_2.setObjectName("label_role_2")
        self.infoTextEdit = QtWidgets.QTextEdit(parent=self.SUMMARY)
        self.infoTextEdit.setGeometry(QtCore.QRect(10, 330, 321, 201))
        self.infoTextEdit.setReadOnly(True)
        self.infoTextEdit.setObjectName("infoTextEdit")
        self.HeroTabWidget.addTab(self.SUMMARY, "")
        self.SKILS = QtWidgets.QWidget()
        self.SKILS.setObjectName("SKILS")
        self.HeroTabWidget.addTab(self.SKILS, "")
        self.GUIDE = QtWidgets.QWidget()
        self.GUIDE.setObjectName("GUIDE")
        self.HeroTabWidget.addTab(self.GUIDE, "")
        self.ADD_NEW_HERO = QtWidgets.QWidget()
        self.ADD_NEW_HERO.setObjectName("ADD_NEW_HERO")
        self.addIcoButton = QtWidgets.QPushButton(parent=self.ADD_NEW_HERO)
        self.addIcoButton.setGeometry(QtCore.QRect(10, 10, 81, 51))
        self.addIcoButton.setText("")
        self.addIcoButton.setObjectName("addIcoButton")
        self.addIcoButton.clicked.connect(self.changeHeroIco)
        self.heroNameLabelAdd = QtWidgets.QLabel(parent=self.ADD_NEW_HERO)
        self.heroNameLabelAdd.setGeometry(QtCore.QRect(100, 10, 71, 16))
        self.heroNameLabelAdd.setObjectName("heroNameLabelAdd")
        self.heroNameLineEdit = QtWidgets.QLineEdit(parent=self.ADD_NEW_HERO)
        self.heroNameLineEdit.setGeometry(QtCore.QRect(100, 40, 221, 22))
        self.heroNameLineEdit.setObjectName("heroNameLineEdit")
        self.heroDescriptionLabel = QtWidgets.QLabel(parent=self.ADD_NEW_HERO)
        self.heroDescriptionLabel.setGeometry(QtCore.QRect(10, 80, 91, 16))
        self.heroDescriptionLabel.setObjectName("heroDescriptionLabel")
        self.heroDescriptionTextEdit = QtWidgets.QTextEdit(parent=self.ADD_NEW_HERO)
        self.heroDescriptionTextEdit.setGeometry(QtCore.QRect(10, 100, 321, 71))
        self.heroDescriptionTextEdit.setObjectName("heroDescriptionTextEdit")
        self.heroTypeLabel = QtWidgets.QLabel(parent=self.ADD_NEW_HERO)
        self.heroTypeLabel.setGeometry(QtCore.QRect(10, 180, 91, 21))
        self.heroTypeLabel.setObjectName("heroTypeLabel")
        self.typeComboBox = QtWidgets.QComboBox(parent=self.ADD_NEW_HERO)
        self.typeComboBox.setGeometry(QtCore.QRect(100, 180, 221, 22))
        self.typeComboBox.setObjectName("typeComboBox")
        self.heroSideLabel = QtWidgets.QLabel(parent=self.ADD_NEW_HERO)
        self.heroSideLabel.setGeometry(QtCore.QRect(10, 210, 91, 21))
        self.heroSideLabel.setObjectName("heroSideLabel")
        self.sideComboBox = QtWidgets.QComboBox(parent=self.ADD_NEW_HERO)
        self.sideComboBox.setGeometry(QtCore.QRect(100, 210, 221, 22))
        self.sideComboBox.setObjectName("sideComboBox")
        self.heroBaseStrLabel = QtWidgets.QLabel(parent=self.ADD_NEW_HERO)
        self.heroBaseStrLabel.setGeometry(QtCore.QRect(10, 250, 101, 21))
        self.heroBaseStrLabel.setObjectName("heroBaseStrLabel")
        self.baseStrSpinBox = QtWidgets.QSpinBox(parent=self.ADD_NEW_HERO)
        self.baseStrSpinBox.setGeometry(QtCore.QRect(130, 250, 42, 22))
        self.baseStrSpinBox.setObjectName("baseStrSpinBox")
        self.baseAglSpinBox = QtWidgets.QSpinBox(parent=self.ADD_NEW_HERO)
        self.baseAglSpinBox.setGeometry(QtCore.QRect(130, 280, 42, 22))
        self.baseAglSpinBox.setObjectName("baseAglSpinBox")
        self.heroBaseAglLabel = QtWidgets.QLabel(parent=self.ADD_NEW_HERO)
        self.heroBaseAglLabel.setGeometry(QtCore.QRect(10, 280, 101, 21))
        self.heroBaseAglLabel.setObjectName("heroBaseAglLabel")
        self.baseIntSpinBox = QtWidgets.QSpinBox(parent=self.ADD_NEW_HERO)
        self.baseIntSpinBox.setGeometry(QtCore.QRect(130, 310, 42, 22))
        self.baseIntSpinBox.setObjectName("baseIntSpinBox")
        self.heroBaseIntLabel = QtWidgets.QLabel(parent=self.ADD_NEW_HERO)
        self.heroBaseIntLabel.setGeometry(QtCore.QRect(10, 310, 121, 21))
        self.heroBaseIntLabel.setObjectName("heroBaseIntLabel")
        self.heroGainStrLabel = QtWidgets.QLabel(parent=self.ADD_NEW_HERO)
        self.heroGainStrLabel.setGeometry(QtCore.QRect(180, 250, 101, 21))
        self.heroGainStrLabel.setObjectName("heroGainStrLabel")
        self.StrDoubleSpinBox = QtWidgets.QDoubleSpinBox(parent=self.ADD_NEW_HERO)
        self.StrDoubleSpinBox.setGeometry(QtCore.QRect(300, 250, 41, 22))
        self.StrDoubleSpinBox.setDecimals(1)
        self.StrDoubleSpinBox.setObjectName("StrDoubleSpinBox")
        self.AglDoubleSpinBox = QtWidgets.QDoubleSpinBox(parent=self.ADD_NEW_HERO)
        self.AglDoubleSpinBox.setGeometry(QtCore.QRect(300, 280, 41, 22))
        self.AglDoubleSpinBox.setDecimals(1)
        self.AglDoubleSpinBox.setObjectName("AglDoubleSpinBox")
        self.heroGainAglLabel = QtWidgets.QLabel(parent=self.ADD_NEW_HERO)
        self.heroGainAglLabel.setGeometry(QtCore.QRect(180, 280, 101, 21))
        self.heroGainAglLabel.setObjectName("heroGainAglLabel")
        self.IntDoubleSpinBox = QtWidgets.QDoubleSpinBox(parent=self.ADD_NEW_HERO)
        self.IntDoubleSpinBox.setGeometry(QtCore.QRect(300, 310, 41, 22))
        self.IntDoubleSpinBox.setDecimals(1)
        self.IntDoubleSpinBox.setObjectName("IntDoubleSpinBox")
        self.heroGainIntLabel = QtWidgets.QLabel(parent=self.ADD_NEW_HERO)
        self.heroGainIntLabel.setGeometry(QtCore.QRect(180, 310, 111, 21))
        self.heroGainIntLabel.setObjectName("heroGainIntLabel")
        self.heroRolesLabel = QtWidgets.QLabel(parent=self.ADD_NEW_HERO)
        self.heroRolesLabel.setGeometry(QtCore.QRect(10, 340, 91, 21))
        self.heroRolesLabel.setObjectName("heroRolesLabel")
        self.rolesTableWidget = QtWidgets.QTableWidget(parent=self.ADD_NEW_HERO)
        self.rolesTableWidget.setGeometry(QtCore.QRect(10, 370, 141, 161))
        self.rolesTableWidget.setObjectName("rolesTableWidget")
        self.rolesTableWidget.setColumnCount(0)
        self.rolesTableWidget.setRowCount(0)
        self.rolesTableWidget.setColumnCount(2)
        self.rolesTableWidget.verticalHeader().setVisible(False)
        self.rolesTableWidget.horizontalHeader().setVisible(False)
        self.addNewHeroButton = QtWidgets.QPushButton(parent=self.ADD_NEW_HERO)
        self.addNewHeroButton.setGeometry(QtCore.QRect(170, 370, 161, 51))
        self.addNewHeroButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(69, 208, 0);")
        self.addNewHeroButton.setObjectName("addNewHeroButton")
        self.HeroTabWidget.addTab(self.ADD_NEW_HERO, "")
        self.aboutHeroLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.aboutHeroLabel.setGeometry(QtCore.QRect(770, 50, 71, 16))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.aboutHeroLabel.setFont(font)
        self.aboutHeroLabel.setStyleSheet("color: rgb(170, 0, 0);")
        self.aboutHeroLabel.setObjectName("aboutHeroLabel")
        self.changeBackgroundButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.changeBackgroundButton.setGeometry(QtCore.QRect(780, 80, 191, 41))
        font = QtGui.QFont()
        font.setFamily("W95FA")
        self.changeBackgroundButton.setFont(font)
        self.changeBackgroundButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(66, 199, 0);\n"
"border-color: rgb(255, 255, 255);")
        self.changeBackgroundButton.setObjectName("changeBackgroundButton")
        self.changeBackgroundButton.clicked.connect(self.setBackground)
        self.strl_layout = QtWidgets.QVBoxLayout(self.strangeLeftFrame)
        self.strl_layout.setContentsMargins(5, 50, 5, 5)  # Отступ сверху для кнопок
        self.strl_layout.setSpacing(5)
        self.strl_layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        self.strr_layout = QtWidgets.QVBoxLayout(self.strangeRightFrame)
        self.strr_layout.setContentsMargins(5, 50, 5, 5)  # Отступ сверху для кнопок
        self.strr_layout.setSpacing(5)
        self.strr_layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        self.agill_layout = QtWidgets.QVBoxLayout(self.agilityLeftFrame)
        self.agill_layout.setContentsMargins(5, 50, 5, 5)  # Отступ сверху для кнопок
        self.agill_layout.setSpacing(5)
        self.agill_layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        self.agilr_layout = QtWidgets.QVBoxLayout(self.agilityRightFrame)
        self.agilr_layout.setContentsMargins(5, 50, 5, 5)  # Отступ сверху для кнопок
        self.agilr_layout.setSpacing(5)
        self.agilr_layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        self.intl_layout = QtWidgets.QVBoxLayout(self.intLeftFrame)
        self.intl_layout.setContentsMargins(5, 50, 5, 5)  # Отступ сверху для кнопок
        self.intl_layout.setSpacing(5)
        self.intl_layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        self.intr_layout = QtWidgets.QVBoxLayout(self.intRightFrame)
        self.intr_layout.setContentsMargins(5, 50, 5, 5)  # Отступ сверху для кнопок
        self.intr_layout.setSpacing(5)
        self.intr_layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        self.backgroundLabel.raise_()
        self.frame.raise_()
        self.profileFrame.raise_()
        self.frame_4.raise_()
        self.chatWidget.raise_()
        self.playButton.raise_()
        self.tabWidget.raise_()
        self.changeBackgroundButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.chatWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.counter = 0

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DotaMenu"))
        self.HeroesButton.setText(_translate("MainWindow", "Heroes"))
        self.pushButton_6.setText(_translate("MainWindow", "Store"))
        self.pushButton_7.setText(_translate("MainWindow", "Watch"))
        self.pushButton_8.setText(_translate("MainWindow", "Learn"))
        self.pushButton_9.setText(_translate("MainWindow", "Arcade"))
        self.gemsLabel.setText(_translate("MainWindow", "0"))
        self.NicknameLabel.setText(_translate("MainWindow", "AAAAAAAAAAAA"))
        self.StatusLabel.setText(_translate("MainWindow", "AAAAAAAA"))
        self.label_6.setText(_translate("MainWindow", "Matches"))
        self.label_7.setText(_translate("MainWindow", "Wins"))
        self.matchesCountLabel.setText(_translate("MainWindow", "0"))
        self.winsCountLabel.setText(_translate("MainWindow", "0"))
        self.chatSendButton.setText(_translate("MainWindow", "SEND"))
        self.chatSendButton.clicked.connect(self.sendMessage)
        self.label_friend.setText(_translate("MainWindow", "INSERT PLAYERS ID:"))
        self.rejectButton.setText(_translate("MainWindow", "REJECT"))
        self.addFriendButton.setText(_translate("MainWindow", "ADD FRIEND"))
        self.searchNickLabel.setText(_translate("MainWindow", "TextLabel"))
        self.searchStatusLabel.setText(_translate("MainWindow", "TextLabel"))
        self.chatLineEdit.setPlaceholderText(_translate("MainWindow", "(All Chat): Type here to chat. Use \'/\' to commands."))
        self.chatWidget.setTabText(self.chatWidget.indexOf(self.tab), _translate("MainWindow", "All Chat"))
        self.playButton.setText(_translate("MainWindow", "PLAY DOTA"))
        self.StatusLabelProfile.setText(_translate("MainWindow", "AAAAAAAA"))
        self.NicknameLabelProfile.setText(_translate("MainWindow", "AAAAAAAAAAAA"))
        self.label_8.setText(_translate("MainWindow", "Matches"))
        self.label_9.setText(_translate("MainWindow", "Wins"))
        self.machesCountProfileLabel.setText(_translate("MainWindow", "0"))
        self.winsCountProfileLabel.setText(_translate("MainWindow", "0"))
        self.label_17.setText(_translate("MainWindow", "In game from"))
        self.label_18.setText(_translate("MainWindow", "Level"))
        self.dateInGameLabel.setText(_translate("MainWindow", "0"))
        self.levelLabel.setText(_translate("MainWindow", "0"))
        self.friendIDLabel.setText(_translate("MainWindow", "FRIEND ID: 0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "PROFILE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "STATS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "TEAMATESS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "TROPHES"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "TICKETS"))
        self.tabWidget.setVisible(False)
        self.changeBackgroundButton.setText(_translate("MainWindow", "CHANGE BACKGROUND IMAGE"))
        self.changeBackgroundButton.setVisible(False)
        self.profileFrame.setVisible(False)
        self.chatWidget.setVisible(False)
        self.playButton.setVisible(False)
        self.frame_4.setVisible(False)
        self.frame.setEnabled(False)
        self.strl.setText(_translate("MainWindow", "STRANGE"))
        self.strr.setText(_translate("MainWindow", "STRANGE"))
        self.agl.setText(_translate("MainWindow", "AGILITY"))
        self.agr.setText(_translate("MainWindow", "AGILITY"))
        self.intr.setText(_translate("MainWindow", "INTELLIGENCE"))
        self.intl.setText(_translate("MainWindow", "INTELLIGENCE"))
        self.heroNameLabel.setText(_translate("MainWindow", "TextLabel"))
        self.sideLabel.setText(_translate("MainWindow", "TextLabel"))
        self.strValueLabel.setText(_translate("MainWindow", "TextLabel"))
        self.aglValueLabel.setText(_translate("MainWindow", "TextLabel"))
        self.intValueLabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_role.setText(_translate("MainWindow", "Role:"))
        self.roleValueLabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_role_2.setText(_translate("MainWindow", "About:"))
        self.HeroTabWidget.setTabText(self.HeroTabWidget.indexOf(self.SUMMARY), _translate("MainWindow", "SUMMARY"))
        self.HeroTabWidget.setTabText(self.HeroTabWidget.indexOf(self.SKILS), _translate("MainWindow", "SKILS"))
        self.HeroTabWidget.setTabText(self.HeroTabWidget.indexOf(self.GUIDE), _translate("MainWindow", "GUIDE"))
        self.heroNameLabelAdd.setText(_translate("MainWindow", "Hero\'s name:"))
        self.heroDescriptionLabel.setText(_translate("MainWindow", "Hero\'s description:"))
        self.heroTypeLabel.setText(_translate("MainWindow", "Hero\'s main type:"))
        self.heroSideLabel.setText(_translate("MainWindow", "Hero\'s main side:"))
        self.heroBaseStrLabel.setText(_translate("MainWindow", "Hero\'s basic strength:"))
        self.heroBaseAglLabel.setText(_translate("MainWindow", "Hero\'s basic agility:"))
        self.heroBaseIntLabel.setText(_translate("MainWindow", "Hero\'s basic intelligence:"))
        self.heroGainStrLabel.setText(_translate("MainWindow", "Hero\'s strength gain:"))
        self.heroGainAglLabel.setText(_translate("MainWindow", "Hero\'s agility gain:"))
        self.heroGainIntLabel.setText(_translate("MainWindow", "Hero\'s intelligence gain:"))
        self.heroRolesLabel.setText(_translate("MainWindow", "Hero\'s roles:"))
        self.addNewHeroButton.setText(_translate("MainWindow", "ADD NEW HERO"))
        self.addNewHeroButton.clicked.connect(self.addNewHero)
        self.HeroTabWidget.setTabText(self.HeroTabWidget.indexOf(self.ADD_NEW_HERO), _translate("MainWindow", "ADD NEW HERO"))
        self.aboutHeroLabel.setText(_translate("MainWindow", "ABOUT HERO: "))
        self.strl.setVisible(False)
        self.strr.setVisible(False)
        self.intl.setVisible(False)
        self.intr.setVisible(False)
        self.agl.setVisible(False)
        self.agr.setVisible(False)
        self.aboutHeroLabel.setVisible(False)
        self.HeroTabWidget.setVisible(False)
        self.strangeLeftFrame.setVisible(False)
        self.strangeRightFrame.setVisible(False)
        self.agilityLeftFrame.setVisible(False)
        self.agilityRightFrame.setVisible(False)
        self.intLeftFrame.setVisible(False)
        self.intRightFrame.setVisible(False)
        self.strl.raise_()
        self.strr.raise_()
        self.intl.raise_()
        self.intr.raise_()
        self.agl.raise_()
        self.agr.raise_()
        self.aboutHeroLabel.raise_()
        self.HeroTabWidget.raise_()
        self.strangeLeftFrame.raise_()
        self.strangeRightFrame.raise_()
        self.agilityLeftFrame.raise_()
        self.agilityRightFrame.raise_()
        self.intLeftFrame.raise_()
        self.intRightFrame.raise_()
        c.execute("SELECT ID,Value FROM type")
        types = c.fetchall()
        self.typeComboBox.addItem("",userData = None)
        for type in types:
            self.typeComboBox.addItem(type[1],userData = type[0])
            
        c.execute("SELECT ID,Value FROM side")
        sides = c.fetchall()
        self.sideComboBox.addItem("",userData = None)
        for side in sides:
            self.sideComboBox.addItem(side[1],userData = side[0])
            

    def showMenu(self):
        
        if not self.profileFrame.isVisible():
            self.friendProfileID = 0
            self.update()
            self.profileFrame.setVisible(True)
            self.chatWidget.setVisible(True)
            self.playButton.setVisible(True)
            self.frame_4.setVisible(True)
            self.tabWidget.setVisible(False)
            self.changeBackgroundButton.setVisible(False)
            self.strl.setVisible(False)
            self.strr.setVisible(False)
            self.intl.setVisible(False)
            self.intr.setVisible(False)
            self.agl.setVisible(False)
            self.agr.setVisible(False)
            self.aboutHeroLabel.setVisible(False)
            self.HeroTabWidget.setVisible(False)
            self.strangeLeftFrame.setVisible(False)
            self.strangeRightFrame.setVisible(False)
            self.agilityLeftFrame.setVisible(False)
            self.agilityRightFrame.setVisible(False)
            self.intLeftFrame.setVisible(False)
            self.intRightFrame.setVisible(False)
        
            
    def initRolesTable(self):
        c.execute("SELECT Value FROM role")
        roles = c.fetchall()
        self.rolesTableWidget.setRowCount(len(roles))
        
        
        
        for i in range(len(roles)):
            role_name = str(roles[i][0])
            item = QtWidgets.QTableWidgetItem(role_name)
            item.setFlags(item.flags() & ~QtCore.Qt.ItemFlag.ItemIsEditable)
            self.rolesTableWidget.setItem(i, 1, item)
            
            checkbox = QtWidgets.QCheckBox()

            
            widget = QtWidgets.QWidget()
            layout = QtWidgets.QHBoxLayout(widget)
            layout.addWidget(checkbox)
            layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
            layout.setContentsMargins(0, 0, 0, 0)
            self.rolesTableWidget.setCellWidget(i, 0, widget)
        
        self.rolesTableWidget.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
        self.rolesTableWidget.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeMode.Stretch)
    def showProfile(self):
        
        if self.profileFrame.isVisible():
            self.profileFrame.setVisible(False)
            self.chatWidget.setVisible(False)
            self.playButton.setVisible(False)
            self.frame_4.setVisible(False)
            self.tabWidget.setVisible(True)
            self.changeBackgroundButton.setVisible(True)
            
    def showHero(self):
        if not self.strl.isVisible():
            self.profileFrame.setVisible(False)
            self.chatWidget.setVisible(False)
            self.playButton.setVisible(False)
            self.frame_4.setVisible(False)
            self.tabWidget.setVisible(False)
            self.changeBackgroundButton.setVisible(False)
            self.strl.setVisible(True)
            self.strr.setVisible(True)
            self.intl.setVisible(True)
            self.intr.setVisible(True)
            self.agl.setVisible(True)
            self.agr.setVisible(True)
            self.aboutHeroLabel.setVisible(True)
            self.HeroTabWidget.setVisible(True)
            self.strangeLeftFrame.setVisible(True)
            self.strangeRightFrame.setVisible(True)
            self.agilityLeftFrame.setVisible(True)
            self.agilityRightFrame.setVisible(True)
            self.intLeftFrame.setVisible(True)
            self.intRightFrame.setVisible(True)
    
    def showFriendProfile(self,fr_id):
        
        self.friendProfileID = fr_id
        self.update()
        if self.profileFrame.isVisible():
            self.profileFrame.setVisible(False)
            self.chatWidget.setVisible(False)
            self.playButton.setVisible(False)
            self.frame_4.setVisible(False)
            self.tabWidget.setVisible(True)
    def setFavourite(self,slot):
        if self.friendProfileID == 0:
            print(slot)
    def changeHeroIco(self):
        global heroImgPath
        file_path, _ = QtWidgets.QFileDialog.getOpenFileName(self.centralwidget, "Выберите файл", "", "All Files (*)")

        if file_path:
            file_extension = os.path.splitext(file_path)[1].lower()
            allowed_extensions = ['.png', '.jpg', '.jpeg']
            if file_extension in allowed_extensions:
                heroImgPath = file_path
            else:
                QtWidgets.QMessageBox.warning(None,"Ошибка","Некоректный тип файла",QtWidgets.QMessageBox.StandardButton.Ok)
        else:
            print("Файл не был выбран")
        
    def Init(self,uID):
        global userID
        userID = uID
        global authDate
        authDate = datetime.now()
        c.execute("UPDATE player SET statusID = 1 WHERE ID = %s",(userID,))
        self.update()
        self.profileFrame.setVisible(True)
        self.chatWidget.setVisible(True)
        self.playButton.setVisible(True)
        self.frame_4.setVisible(True)
        self.frame.setEnabled(True)
        self.InitHeroDescription()
        self.InitHeroTables()
        self.initRolesTable()
        
    def InitHeroDescription(self):
        c.execute("SELECT name,description,sideID,typeID,picturePath,baseStrange,baseAgility,baseIntelect,strUpValue,agilUpValue,intUpValue FROM heroes WHERE ID = %s",(currentHeroID,))
        results = c.fetchone()
        c.execute("SELECT roleID FROM herorolelist WHERE heroID = %s",(currentHeroID,))
        roles = c.fetchall()
        if results[4] != None:
            self.heroIcoLabel.setPixmap(QtGui.QPixmap(results[4]))
            self.heroIcoLabel.setScaledContents(True)
        self.heroNameLabel.setText(results[0])
        self.heroNameLabel.adjustSize()
        self.strValueLabel.setText(f"{results[5]} + {results[8]}")
        self.aglValueLabel.setText(f"{results[6]} + {results[9]}")
        self.intValueLabel.setText(f"{results[7]} + {results[10]}")
        self.strValueLabel.adjustSize()
        self.aglValueLabel.adjustSize()
        self.intValueLabel.adjustSize()
        rolestr = ""
        for role in roles:
            c.execute("SELECT Value FROM role WHERE ID = %s",(role[0],))
            rolestr += f"{c.fetchone()[0]}, "
        rolestr = rolestr[0:-2:1]
        self.roleValueLabel.setText(rolestr)
        self.roleValueLabel.adjustSize()
        self.infoTextEdit.clear()
        self.infoTextEdit.append(results[1])
        
    def InitHeroTables(self):
    # Очищаем все layout
        self.clear_hero_layouts()
        
        # Настраиваем выравнивание для всех layout
        for layout in [self.strl_layout, self.strr_layout, self.agill_layout, 
                    self.agilr_layout, self.intl_layout, self.intr_layout]:
            layout.setSpacing(2)
            layout.setContentsMargins(0, 0, 0, 0)
            layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop | QtCore.Qt.AlignmentFlag.AlignLeft)
        
        c.execute("SELECT ID,picturePath,sideID,typeID FROM heroes")
        results = c.fetchall()
        
        # Группируем героев
        categories = {
            'strleft': [], 'strright': [],
            'agilleft': [], 'agilright': [],
            'intleft': [], 'intright': []
        }
        
        for res in results:
            hero_id, pic_path, side_id, type_id = res
            
            if side_id == 1 and type_id == 1:
                categories['strleft'].append([hero_id, pic_path])
            elif side_id == 2 and type_id == 1:
                categories['strright'].append([hero_id, pic_path])
            elif side_id == 1 and type_id == 2:
                categories['agilleft'].append([hero_id, pic_path])
            elif side_id == 2 and type_id == 2:
                categories['agilright'].append([hero_id, pic_path])
            elif side_id == 1 and type_id == 3:
                categories['intleft'].append([hero_id, pic_path])
            elif side_id == 2 and type_id == 3:
                categories['intright'].append([hero_id, pic_path])
        
        # Добавляем героев в layout
        for category_name, hero_list in categories.items():
            layout_map = {
                'strleft': self.strl_layout,
                'strright': self.strr_layout,
                'agilleft': self.agill_layout,
                'agilright': self.agilr_layout,
                'intleft': self.intl_layout,
                'intright': self.intr_layout
            }
            
            layout = layout_map[category_name]
            self.add_heroes_to_layout_simple(hero_list, layout)

    def add_heroes_to_layout_simple(self, hero_list, layout):
        """Простая версия добавления героев с выравниванием в левом верхнем углу"""
        if not hero_list:
            return
        
        # Уменьшенные размеры кнопки
        button_width = 80
        button_height = 60
        buttons_per_row = 3  # 291px / 80px ≈ 3 кнопки в строке
        
        # Создаем виджет-контейнер с GridLayout
        container = QtWidgets.QWidget()
        grid_layout = QtWidgets.QGridLayout(container)
        grid_layout.setSpacing(2)
        grid_layout.setContentsMargins(0, 0, 0, 0)
        
        row = 0
        col = 0
        
        for hero in hero_list:
            # Создаем кнопку
            hero_button = QtWidgets.QPushButton()
            hero_button.setFixedSize(button_width, button_height)
            
            # Стиль без рамок
            hero_button.setStyleSheet("""
                QPushButton {
                    border: none;
                    padding: 0px;
                    background-color: transparent;
                }
                QPushButton:hover {
                    border: 2px solid #ff6600;
                }
            """)
            
            # Загружаем иконку
            if hero[1] and os.path.exists(hero[1]):
                try:
                    pixmap = QtGui.QPixmap(hero[1])
                    # Масштабируем изображение
                    scaled_pixmap = pixmap.scaled(
                        button_width, 
                        button_height,
                        QtCore.Qt.AspectRatioMode.KeepAspectRatio,
                        QtCore.Qt.TransformationMode.SmoothTransformation
                    )
                    
                    # Создаем кнопку с иконкой, которая полностью заполняет кнопку
                    hero_button.setIcon(QtGui.QIcon(scaled_pixmap))
                    hero_button.setIconSize(QtCore.QSize(button_width, button_height))
                except:
                    hero_button.setText(str(hero[0]))
            else:
                hero_button.setText(str(hero[0]))
            
            # Подключаем клик
            hero_button.clicked.connect(lambda checked, hid=hero[0]: self.changeHeroID(hid))
            
            # Добавляем в grid
            grid_layout.addWidget(hero_button, row, col)
            
            # Обновляем позицию
            col += 1
            if col >= buttons_per_row:
                col = 0
                row += 1
        
        # Добавляем контейнер в основной layout
        layout.addWidget(container)
    def clear_layout(self, layout):
        """Очищает layout от всех виджетов"""
        if layout is not None:
            while layout.count():
                item = layout.takeAt(0)
                widget = item.widget()
                if widget is not None:
                    widget.deleteLater()
    def clear_hero_layouts(self):
        """Очищает все layout с героями"""
        layouts = [
            self.strl_layout, self.strr_layout,
            self.agill_layout, self.agilr_layout,
            self.intl_layout, self.intr_layout
        ]
        
        for layout in layouts:
            self.clear_layout(layout)
  
    def changeHeroID(self,hid):
        global currentHeroID
        currentHeroID = int(hid)
        self.InitHeroDescription()
    
    def addNewHero(self):
        global heroImgPath
        name = self.heroNameLineEdit.text()
        description = self.heroDescriptionTextEdit.toPlainText()
        heroType = self.typeComboBox.currentData()
        heroSide = self.sideComboBox.currentData()
        baseStrange = self.baseStrSpinBox.value()
        baseAgility = self.baseAglSpinBox.value()
        baseIntelligence = self.baseIntSpinBox.value()
        upStr = self.StrDoubleSpinBox.value()
        upAgl = self.AglDoubleSpinBox.value()
        upInt = self.IntDoubleSpinBox.value()
        tableRowCount = self.rolesTableWidget.rowCount()
        roles = []
        for i in range(tableRowCount):
            widget = self.rolesTableWidget.cellWidget(i, 0)
            if widget is not None:
                checkbox = widget.findChild(QtWidgets.QCheckBox)
                if checkbox and checkbox.isChecked():
                    role_item = self.rolesTableWidget.item(i, 1)
                    if role_item is not None:
                        roles.append(role_item.text())
        
        if name.strip() != "" and description.strip() != "" and heroImgPath != None and heroType != None and heroSide != None and len(roles) > 0:
            c.execute("INSERT INTO heroes(name,description,sideID,typeID,picturePath,baseStrange,baseAgility,baseIntelect,strUpValue,agilUpValue,intUpValue) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)",(name,description,heroSide,heroType,heroImgPath,baseStrange,baseAgility,baseIntelligence,upStr,upAgl,upInt,))
            c.execute("SELECT LAST_INSERT_ID()")
            hid = c.fetchone()[0]
            for role in roles:
                c.execute("SELECT ID FROM role WHERE Value = %s",(role,))
                roleID = c.fetchone()[0]
                c.execute("INSERT INTO herorolelist(heroID,roleID) VALUES(%s,%s)",(hid,roleID,))
            self.InitHeroTables()
            self.initRolesTable()
            heroImgPath = None
            self.heroNameLineEdit.setText('')
            self.heroDescriptionTextEdit.clear()
            self.typeComboBox.setCurrentIndex(0)
            self.sideComboBox.setCurrentIndex(0)
            self.baseStrSpinBox.setValue(0)
            self.baseAglSpinBox.setValue(0)
            self.baseIntSpinBox.setValue(0)
            self.StrDoubleSpinBox.setValue(0.0)
            self.AglDoubleSpinBox.setValue(0.0)
            self.IntDoubleSpinBox.setValue(0.0)
        else:
            QtWidgets.QMessageBox.warning(None,"Ошибка","Данные заполнены некорректно",QtWidgets.QMessageBox.StandardButton.Ok)
        
    
    def add_friend_to_frame(self, friend_id, nickname, status_id, avatar_path):
        """Добавляет элемент друга на фрейм"""
        
        friend_widget = QtWidgets.QFrame()
        friend_widget.setFrameShape(QtWidgets.QFrame.Shape.Box)
        friend_widget.setLineWidth(1)
        friend_widget.setFixedHeight(60)
        
        
        
        friend_layout = QtWidgets.QHBoxLayout(friend_widget)
        friend_layout.setContentsMargins(5, 5, 5, 5)
        friend_layout.setSpacing(10)
        
        
        avatar_button = QtWidgets.QPushButton()
        avatar_button.setFixedSize(50, 50)
        
        
        
        avatar_button.setIcon(QtGui.QIcon(avatar_path))
        
        
        avatar_button.setIconSize(QtCore.QSize(45, 45))
        
        
        
        labels_widget = QtWidgets.QWidget()
        labels_layout = QtWidgets.QVBoxLayout(labels_widget)
        labels_layout.setContentsMargins(0, 0, 0, 0)
        labels_layout.setSpacing(2)
        
        
        nickname_label = QtWidgets.QLabel(nickname)
       
        
        
        c.execute("SELECT Value FROM playerstatus WHERE ID = %s", (status_id,))
        status_text = c.fetchone()[0]
        status_label = QtWidgets.QLabel(status_text)
        
        
        labels_layout.addWidget(nickname_label)
        labels_layout.addWidget(status_label)
        
        
        
        
        avatar_button.clicked.connect(lambda : self.showFriendProfile(friend_id))
        
        friend_layout.addWidget(avatar_button)
        friend_layout.addWidget(labels_widget, 1)  
        
        

        self.frame_main_layout.addWidget(friend_widget)
    
    
    
    def clear_frame(self):
        """Полностью очищает фрейм с друзьями"""
        
        while self.frame_main_layout.count():
            item = self.frame_main_layout.takeAt(0)
            widget = item.widget()
            if widget:
                widget.deleteLater()
    
    def refresh_friends_list(self):
        """Обновляет список друзей на фрейме"""
       
        self.clear_frame()
        
       
        c.execute("SELECT friendID FROM friendlist WHERE playerID = %s",(userID,))
        friends = c.fetchall()
        
        for friend in friends:
            friend_id = friend[0]
            c.execute("SELECT nickname, statusID, avatarPath FROM player WHERE ID = %s", (friend_id,))
            friend_info = c.fetchone()
            
            if friend_info:
                self.add_friend_to_frame(friend_id, friend_info[0], friend_info[1], friend_info[2])
        
    def deleteFriend(self):
        reply = QtWidgets.QMessageBox.question(None,"Подтверждение","Вы уверены?",QtWidgets.QMessageBox.StandardButton.Yes | QtWidgets.QMessageBox.StandardButton.No)
        if reply == QtWidgets.QMessageBox.StandardButton.Yes:
            c.execute("DELETE FROM friendlist WHERE playerID = %s AND friendID = %s",(userID,self.friendProfileID,))
            c.execute("DELETE FROM friendlist WHERE playerID = %s AND friendID = %s",(self.friendProfileID,userID,))
            self.showMenu()
        
    def update(self):
        c.execute("SELECT nickname,winValue,looseValue,ratingValue,cristalsValue,avatarPath,statusID,backgroundPath,level,DateCreate FROM player WHERE ID = %s",(userID,))
        results = c.fetchone()
        self.gemsLabel.setText(str(results[4]))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(results[5]), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.profileButton.setIcon(icon7)
        self.profileButton.setIconSize(QtCore.QSize(52, 52))

        self.matchesCountLabel.setText(str(int(results[1])+int(results[2])))
        
        self.winsCountLabel.setText(str(results[1]))
        
        self.NicknameLabel.setText(results[0])
        
        c.execute("SELECT Value FROM playerstatus WHERE ID = %s",(results[6],))
        status = c.fetchone()[0]
        
        self.StatusLabel.setText(status)
        
        mmr = int(results[3])
        mmrIco = "noTitle.png"
        match mmr:
            case r if r>=1 and r<=700:
                mmrIco = "recrut.png"
            case r if r>=701 and r<=1400:
                mmrIco = "straj.png"
            case r if r>=1401 and r<=2100:
                mmrIco = "ritchar.png"
            case r if r>=2101 and r<=2950:
                mmrIco = "hero.png"
            case r if r>=2951 and r<=3700:
                mmrIco = "legenda.png"
            case r if r>=3701 and r<=4600:
                mmrIco = "vlastelin.png"
            case r if r>=4601 and r<=5600:
                mmrIco = "god.png"
            case r if r>5600:
                mmrIco = "tityan.png"
            case _:
                pass
        self.mmrIcoLabel.setPixmap(QtGui.QPixmap(mmrIco))
        self.mmrIcoLabel.setScaledContents(True)
        if heroImgPath != None:
            icon11 = QtGui.QIcon()
            icon11.addPixmap(QtGui.QPixmap(heroImgPath), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
            self.addIcoButton.setIcon(icon11)
            self.addIcoButton.setIconSize(QtCore.QSize(77, 69))
        else:
            icon12 = QtGui.QIcon()
            self.addIcoButton.setIcon(icon12)
            
        
        
        self.clear_frame()
        c.execute("SELECT friendID FROM friendlist WHERE playerID = %s",(userID,))
        friends = c.fetchall()

        for friend in friends:
            friend_id = friend[0]
            
            # Получаем информацию о друге
            c.execute("SELECT nickname, statusID, avatarPath FROM player WHERE ID = %s", (friend_id,))
            friend_info = c.fetchone()
            
            if friend_info:
                self.add_friend_to_frame(friend_id, friend_info[0], friend_info[1], friend_info[2])
        
        if self.friendProfileID == 0:
            self.deleteFriendButton.setVisible(False)
            self.addedFriendLabel.setVisible(False)
            self.mmrIcoProfileLabel.setPixmap(QtGui.QPixmap(mmrIco))
            self.mmrIcoProfileLabel.setScaledContents(True)
            if results[7] != None:
                self.backgroundLabel.setPixmap(QtGui.QPixmap(results[7]))
                self.backgroundLabel.setScaledContents(True)
            else:
                self.backgroundLabel.clear()
            self.profileButtonProfile.setIcon(icon7)
            self.profileButtonProfile.setIconSize(QtCore.QSize(128,128))
            self.NicknameLabelProfile.setText(results[0])
            self.machesCountProfileLabel.setText(str(int(results[1])+int(results[2])))
            self.winsCountProfileLabel.setText(str(results[1]))
            self.StatusLabelProfile.setText(status)
            self.friendIDLabel.setText(f"FRIEND ID: {userID}")
            self.levelLabel.setText(str(results[8]))
            dt = results[9]
            self.dateInGameLabel.setText(dt.strftime('%d.%m.%Y'))
        
        else:
            c.execute("SELECT nickname,winValue,looseValue,ratingValue,cristalsValue,avatarPath,statusID,backgroundPath,level,DateCreate FROM player WHERE ID = %s",(self.friendProfileID,))
            frResults = c.fetchone()
            mmr = int(frResults[3])
            mmrIco = "noTitle.png"
            match mmr:
                case r if r>=1 and r<=700:
                    mmrIco = "recrut.png"
                case r if r>=701 and r<=1400:
                    mmrIco = "straj.png"
                case r if r>=1401 and r<=2100:
                    mmrIco = "ritchar.png"
                case r if r>=2101 and r<=2950:
                    mmrIco = "hero.png"
                case r if r>=2951 and r<=3700:
                    mmrIco = "legenda.png"
                case r if r>=3701 and r<=4600:
                    mmrIco = "vlastelin.png"
                case r if r>=4601 and r<=5600:
                    mmrIco = "god.png"
                case r if r>5600:
                    mmrIco = "tityan.png"
                case _:
                    pass
            self.mmrIcoProfileLabel.setPixmap(QtGui.QPixmap(mmrIco))
            self.mmrIcoProfileLabel.setScaledContents(True)
            if frResults[7] != None:
                self.backgroundLabel.setPixmap(QtGui.QPixmap(frResults[7]))
                self.backgroundLabel.setScaledContents(True)
            else:
                self.backgroundLabel.clear()
            icon10 = QtGui.QIcon()
            icon10.addPixmap(QtGui.QPixmap(frResults[5]), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
            self.profileButtonProfile.setIcon(icon10)
            self.profileButtonProfile.setIconSize(QtCore.QSize(128,128))
            self.NicknameLabelProfile.setText(frResults[0])
            self.machesCountProfileLabel.setText(str(int(frResults[1])+int(frResults[2])))
            self.winsCountProfileLabel.setText(str(frResults[1]))
            c.execute("SELECT Value FROM playerstatus WHERE ID = %s",(frResults[6],))
            status = c.fetchone()[0]
            self.StatusLabelProfile.setText(status)
            self.friendIDLabel.setText(f"FRIEND ID: {self.friendProfileID}")
            self.levelLabel.setText(str(frResults[8]))
            dt = frResults[9]
            self.dateInGameLabel.setText(dt.strftime('%d.%m.%Y'))
            self.deleteFriendButton.setVisible(True)
            self.addedFriendLabel.setVisible(True)
            c.execute("SELECT DateAdded FROM friendlist WHERE playerID = %s AND friendID = %s",(userID,self.friendProfileID,))
            self.addedFriendLabel.setText(f"Added to friendlist from {c.fetchone()[0].strftime('%d.%m.%Y')}")
            self.addedFriendLabel.adjustSize()
            
    def updateChat(self):
        self.chatTextEdit.clear()
        self.chatMessages.clear()
        c.execute("SELECT CONCAT(player.nickname,' at ', playerchat.DateSend, ' ', playerchat.text) FROM playerchat INNER JOIN player ON playerchat.playerID = player.ID WHERE playerchat.DateSend > %s ORDER BY playerchat.DateSend",(authDate,))
        messages = c.fetchall()
        c.execute("SELECT nickname FROM player")
        nicks = c.fetchall()
        for message in messages:
            self.chatMessages.append(message[0])
        for nick in nicks:
            self.chatTextEdit.append(nick[0])
            
    def sendMessage(self):
        if self.chatLineEdit.text().strip() == "":
            QtWidgets.QMessageBox.warning(None,"Ошибка","Текст не может быть пустым", QtWidgets.QMessageBox.StandardButton.Ok)
        else:
            currentDate = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            c.execute("INSERT INTO playerchat(playerID,text,DateSend) VALUES(%s,%s,%s)",(userID,self.chatLineEdit.text(),currentDate,))
            self.updateChat()
            self.chatLineEdit.clear()
            
    
    def changeAvatar(self):
        self.click_count += 1
        if self.click_count == 1:
            self.click_timer.start(300)
        elif self.click_count == 2:
            file_path, _ = QtWidgets.QFileDialog.getOpenFileName(self.centralwidget, "Выберите файл", "", "All Files (*)")

            if file_path:
                file_extension = os.path.splitext(file_path)[1].lower()
                allowed_extensions = ['.png', '.jpg', '.jpeg']
                if file_extension in allowed_extensions:
                    c.execute("UPDATE player SET avatarPath = %s WHERE ID = %s",(file_path,userID,))
                else:
                    QtWidgets.QMessageBox.warning(None,"Ошибка","Некоректный тип файла",QtWidgets.QMessageBox.StandardButton.Ok)
            else:
                print("Файл не был выбран")
            
            
            
            self.click_timer.stop() 
            self.reset_click_count()

    def reset_click_count(self):
        self.click_count = 0
    
    def openAddFriend(self):
        self.addFriendFrame.setVisible(True)
        self.addFriendFrame.raise_()
    
    def closeAddFriend(self):
        self.addFriendFrame.setVisible(False)
        
    def searchFriend(self):
        friendID = self.searchFriendLineEdit.text()
        currentFriends = []
        c.execute("SELECT friendID FROM friendlist WHERE playerID = %s",(userID,))
        res = c.fetchall()
        if res != None:
            for r in res:
                currentFriends.append(r[0])
        print(currentFriends)
        if friendID != "":
            if int(friendID) != userID and int(friendID) not in currentFriends:
                c.execute("SELECT nickname,statusID,avatarPath FROM player WHERE ID = %s",(friendID,))
                res = c.fetchone()
                if res == None:
                    self.searchAvatarlabel.setVisible(False)
                    self.searchNickLabel.setVisible(False)
                    self.searchStatusLabel.setVisible(False)
                    self.addFriendButton.setVisible(False)
                else:
                    self.addFriendButton.setVisible(True)
                    
                    self.searchNickLabel.setText(res[0])
                    self.searchNickLabel.adjustSize()
                    c.execute("SELECT Value FROM playerstatus WHERE ID = %s",(res[1],))
                    self.searchStatusLabel.setText(c.fetchone()[0])
                    self.searchStatusLabel.adjustSize()
                    self.searchAvatarlabel.setPixmap(QtGui.QPixmap(res[2]))
                    self.searchAvatarlabel.setScaledContents(True)
                    self.searchAvatarlabel.setVisible(True)
                    self.searchNickLabel.setVisible(True)
                    self.searchStatusLabel.setVisible(True)
            else:
                self.searchAvatarlabel.setVisible(False)
                self.searchNickLabel.setVisible(False)
                self.searchStatusLabel.setVisible(False)
                self.addFriendButton.setVisible(False)
        else:
            self.searchAvatarlabel.setVisible(False)
            self.searchNickLabel.setVisible(False)
            self.searchStatusLabel.setVisible(False)
            self.addFriendButton.setVisible(False)
                    
    def addFriend(self):
        currentDate = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        c.execute("INSERT INTO friendlist(playerID,friendID,DateAdded) VALUES(%s,%s,%s)",(userID,int(self.searchFriendLineEdit.text()),currentDate,))
        c.execute("INSERT INTO friendlist(playerID,friendID,DateAdded) VALUES(%s,%s,%s)",(int(self.searchFriendLineEdit.text()),userID,currentDate,))
        self.searchFriendLineEdit.clear()
        self.addFriendFrame.setVisible(False)
        self.refresh_friends_list()
    
    def setBackground(self):
        file_path, _ = QtWidgets.QFileDialog.getOpenFileName(self.centralwidget, "Выберите файл", "", "All Files (*)")

        if file_path:
            file_extension = os.path.splitext(file_path)[1].lower()
            allowed_extensions = ['.png', '.jpg', '.jpeg']
            if file_extension in allowed_extensions:
                c.execute("UPDATE player SET backgroundPath = %s WHERE ID = %s",(file_path,userID,))
            else:
                QtWidgets.QMessageBox.warning(None,"Ошибка","Некоректный тип файла",QtWidgets.QMessageBox.StandardButton.Ok)
        else:
            print("Файл не был выбран")
    
    def globalUpdate(self):
        if userID != None: 
            self.update()
            self.updateChat()
            
    def closeEvent(self, event):
        c.execute("UPDATE player SET statusID = 5 WHERE ID = %s",(userID,))
        event.accept()

